Repository godotengine/godot-cpp-template, pull requests merged in 2024-09, with the labels that each got.

#37 Print an error if the godot-cpp submodule hasn't been initialized
  SConstruct
  methods.py
Labels: enhancement

#43 Fix macos demo build target in SConstruct
  SConstruct
Labels: bug

#48 Remove invalid production=yes flag from github action
  .github/actions/build/action.yml
Labels: bug

#53 Update example.gdextension to match default build artifacts
  demo/bin/example.gdextension
Labels: enhancement

#52 Replace remaining references to `ClassDB::register_class()` with `GDREGISTER_CLASS()`
  README.md
  src/register_types.cpp
Labels: documentation, enhancement

#51 Ignore files generated for documentation
  .gitignore
Labels: enhancement
